name = "fathom-webhook"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "KV"
id = "4e63db1305a1424ead3565522a47b5f4"

[[d1_databases]]
binding = "DB"
database_name = "mahler-db"
database_id = "b6cb2eac-2903-46bd-baea-b4ff2dc904d0"
